### ISSUE TITLE
[PLAN] App Command Default Permissions

### ISSUE THREAD

**Issue by TwilightZebby** [TwilightZebby/MooBot#91]
Now that Discord has fully released Application Commands Permissions v2, here is my plans for what [default command permissions](https://discord.com/developers/docs/interactions/application-commands#application-command-permissions-object-using-default-permissions) I will have for MooBot's Commands, in addition to if they will be usable in DMs or not.

| Command Name        | Command Type | Default Permission Requirement | Usable in DMs? |
|---------------------|--------------|--------------------------------|----------------|
| boop                | Slash        | -                              | FALSE          |
| bonk                | Slash        | -                              | FALSE          |
| headpat             | Slash        | -                              | FALSE          |
| hug                 | Slash        | -                              | FALSE          |
| info                | Slash        | -                              | TRUE\*         |
| kiss                | Slash        | -                              | FALSE          |
| potato              | Slash        | CREATE_PUBLIC_THREADS\*\*      | FALSE          |
| pummel              | Slash        | -                              | FALSE          |
| rolemenu            | Slash        | MANAGE_ROLES                   | FALSE          |
| rule\*\*\*          | Slash        | -                              | N/A            |
| slap                | Slash        | -                              | FALSE          |
| sleep               | Slash        | -                              | FALSE          |
| start               | Slash        | START_EMBEDDED_ACTIVITIES      | FALSE          |
| temperature         | Slash        | -                              | TRUE           |
| Convert Temperature | Message      | -                              | FALSE          |

\* While `/info` will be usable in DMs with the Bot, it's `/info server` subcommand will instead bring up an error due to expecting to be used within a Server. This error will be an intended change.

\*\* The `/potato` Command will require the `CREATE_PUBLIC_THREADS` Permission in preparation for a planned update to said Command.

\*\*\* The `/rule` Command will *not* be a Global Command, instead only be registered and usable within [Dr1fterX's Discord Server](https://discord.gg/URH5E34FZf). Furthermore, due to being a Guild Command, it will not have the ability to set a `dm_permission` flag, as described on [Discord's API Documentation](https://discord.com/developers/docs/interactions/application-commands#application-command-permissions-object-using-default-permissions)

**Comment by EthanUltra** [comment]
There should be a falcon punch command.

Just saying lol
